name: Build Nightly
on:
  push:
    branches: [dev]

# Define required permissions
permissions:
  contents: write  # Needed for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install semver

      - name: Create nightly package
        run: |
          mkdir -p dist
          python src/scripts/build_package.py --channel=nightly
          # Đổi tên file zip để có tên cố định cho việc tải xuống
          # Bản gốc vẫn giữ nguyên, tạo thêm một bản copy với tên cố định
          find dist -name "*.zip" -type f -exec cp {} dist/wpdocker-nightly-latest.zip \;
          ls -la dist/

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Delete existing nightly release assets
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const releaseTag = 'nightly';
            try {
              // Get the existing release by tag
              const { data: release } = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: releaseTag
              });

              // Delete all existing assets
              if (release.assets && release.assets.length > 0) {
                console.log(`Found existing release with ${release.assets.length} assets. Deleting...`);

                for (const asset of release.assets) {
                  console.log(`Deleting asset: ${asset.name} (ID: ${asset.id})`);
                  await github.rest.repos.deleteReleaseAsset({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    asset_id: asset.id
                  });
                }
                console.log('All existing assets deleted successfully.');
              } else {
                console.log('No existing assets to delete.');
              }
            } catch (error) {
              if (error.status === 404) {
                console.log(`No existing release found with tag '${releaseTag}'. Will create a new one.`);
              } else {
                console.error(`Error: ${error.message}`);
              }
            }

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          name: "Nightly Build - ${{ steps.date.outputs.date }}"
          tag_name: nightly
          prerelease: true
          generate_release_notes: true
          body: |
            ## Automated nightly build from dev branch
            Build date: ${{ steps.date.outputs.date }}

            ### Tải xuống nhanh
            Sử dụng file wpdocker-nightly-latest.zip để luôn nhận bản build mới nhất.

            ## Release Notes
            *Automatically generated release notes appear below:*